apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: backend-seguros
data:
  SERVER_PORT: "8080"
  SPRING_RABBITMQ_HOST: "rabbitmq-service.backend-seguros.svc.cluster.local"
  SPRING_RABBITMQ_PORT: "5672"
  WHATSAPP_BASE_URL: "https://api.whatsapp.json.pe"
  WHATSAPP_TIMEOUT_SECONDS: "5"
  WHATSAPP_CB_WAIT_OPEN: "30s"
