<script setup lang="ts">
import {onMounted,ref} from 'vue';import {useRoute,useRouter} from 'vue-router';import {useAuthStore} from '@/stores/auth';import {errorMessage} from '@/services/api';import {facebookLoginUrl} from '@/services/facebookAuth';import type {GoogleCredentialResponse} from '@/types';
const u=ref('admin'),p=ref('Admin123*'),loading=ref(false),error=ref('');const a=useAuthStore(),r=useRouter(),ruta=useRoute();
async function go(){loading.value=true;error.value='';try{const ok=await a.login(u.value.trim(),p.value);r.push(ok?(a.role==='CLIENTE'?'/mi-cuenta':'/dashboard'):'/mfa-verification')}catch(e){error.value=errorMessage(e)}finally{loading.value=false}}
async function onGoogleCredential(response:GoogleCredentialResponse){loading.value=true;error.value='';try{await a.loginWithGoogle(response.credential);r.push(a.role==='CLIENTE'?'/mi-cuenta':'/dashboard')}catch(e){error.value=errorMessage(e)}finally{loading.value=false}}
// El backend gestiona todo el intercambio OAuth (code/state/App Secret); el frontend solo redirige.
function onFacebookLogin(){window.location.assign(facebookLoginUrl())}
async function onFacebookTicket(ticket:string){loading.value=true;error.value='';try{await a.exchangeFacebookTicket(ticket);await r.replace({path:'/login',query:{}});r.push(a.role==='CLIENTE'?'/mi-cuenta':'/dashboard')}catch(e){await r.replace({path:'/login',query:{}});error.value=errorMessage(e)}finally{loading.value=false}}
onMounted(()=>{
  const ticket=ruta.query.ticket;
  if(typeof ticket==='string'&&ticket){onFacebookTicket(ticket);return}
  if(ruta.query.error){r.replace({path:'/login',query:{}});error.value='No se pudo completar el inicio de sesión con Facebook.'}
});
onMounted(()=>{let intentos=0;const timer=setInterval(()=>{const google=(window as any).google;if(google){clearInterval(timer);const contenedor=document.getElementById('google-btn');google.accounts.id.initialize({client_id:import.meta.env.VITE_GOOGLE_CLIENT_ID,callback:onGoogleCredential});google.accounts.id.renderButton(contenedor,{theme:'outline',size:'large',shape:'pill',width:contenedor?.parentElement?.offsetWidth||320,text:'continue_with',logo_alignment:'center'})}else if(++intentos>50){clearInterval(timer)}},100)});
</script>
<template><div class="login-page"><div class="login-art"><div class="art-copy"><span class="eyebrow">Plataforma aseguradora</span><h1>Decisiones de riesgo claras, rápidas y trazables.</h1><p>Centraliza cotizaciones, emisión, siniestros y renovaciones con una experiencia simple.</p><div class="art-metrics"><div><b>100%</b><span>Trazabilidad</span></div><div><b>Clean</b><span>Arquitectura</span></div><div><b>24/7</b><span>Disponibilidad</span></div></div></div></div><div class="login-panel"><form class="login-card" @submit.prevent="go"><div class="logo-large">A</div><h2>Bienvenido</h2><p>Ingresa para administrar Andina Seguros.</p><label>Usuario<input v-model="u" autocomplete="username" required/></label><label>Contraseña<input v-model="p" type="password" autocomplete="current-password" required/></label><div v-if="error" class="alert error">{{error}}</div><button class="primary wide" :disabled="loading">{{loading?'Ingresando…':'Iniciar sesión'}}</button><div class="google-divider"><span>o</span></div><button type="button" class="fb-btn" :disabled="loading" @click="onFacebookLogin"><svg viewBox="0 0 24 24" aria-hidden="true"><path fill="#1877F2" d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/></svg><span>Continuar con Facebook</span></button><div id="google-btn"></div><small>Usuario inicial sugerido: admin / Admin123*</small></form></div></div></template>
