<script setup lang="ts">
import {computed,onMounted,reactive,ref}from'vue';import{useRoute}from'vue-router';import api,{errorMessage}from'@/services/api';import type{Cliente,Cotizacion,Poliza,Siniestro,Vehiculo}from'@/types';import UiModal from'@/components/UiModal.vue';import StatusBadge from'@/components/StatusBadge.vue';
const list=ref<Poliza[]>([]),pending=ref<Cotizacion[]>([]),clients=ref<Cliente[]>([]),vehicles=ref<Vehiculo[]>([]),sin=ref<Record<string,Siniestro[]>>({}),show=ref(false),selected=ref<Poliza|null>(null),msg=ref(''),success=ref(''),updating=ref(''),renewing=ref(''),estado=ref('');const stateEdits=reactive<Record<string,string>>({});const route=useRoute();
const emit=reactive({cotizacionId:String(route.query.cotizacionId||''),inicioVigencia:new Date().toISOString().slice(0,10)});const f=reactive({polizaId:'',fecha:new Date().toISOString().slice(0,10),tipo:'COLISION',montoEstimado:1000,responsabilidadAsegurado:false,gravedad:'LEVE',estado:'REPORTADO'});
const clientMap=computed(()=>new Map(clients.value.map(x=>[x.id,`${x.nombres} ${x.apellidos}`])));const vehicleMap=computed(()=>new Map(vehicles.value.map(x=>[x.id,`${x.placa} · ${x.marca} ${x.modelo}`])));
function quoteLabel(q:Cotizacion){return `${q.numero} — ${clientMap.value.get(q.clienteId)||'Cliente'} — ${vehicleMap.value.get(q.vehiculoId)||'Vehículo'} — ${q.moneda} ${Number(q.prima).toFixed(2)}`}
async function load(){msg.value='';try{list.value=(await api.get('/polizas',{params:{estado:estado.value||undefined}})).data}catch(e){msg.value=errorMessage(e)}}
async function loadPending(){pending.value=(await api.get('/cotizaciones/pendientes-emision')).data;if(emit.cotizacionId&&!pending.value.some(q=>q.id===emit.cotizacionId))emit.cotizacionId=''}
async function loadCatalogs(){clients.value=(await api.get('/clientes')).data;const groups=await Promise.all(clients.value.map(async c=>(await api.get(`/clientes/${c.id}/vehiculos`)).data as Vehiculo[]));vehicles.value=groups.flat()}
async function issue(){msg.value='';success.value='';try{await api.post('/polizas',emit);success.value='Póliza emitida correctamente.';emit.cotizacionId='';await Promise.all([load(),loadPending()])}catch(e){msg.value=errorMessage(e)}}
async function loadClaims(policyId:string){sin.value[policyId]=(await api.get(`/polizas/${policyId}/siniestros`)).data;sin.value[policyId].forEach(x=>stateEdits[x.id]=x.estado)}
async function open(p:Poliza){selected.value=p;f.polizaId=p.id;show.value=true;msg.value='';try{await loadClaims(p.id)}catch(e){msg.value=errorMessage(e)}}
async function saveS(){try{await api.post(`/polizas/${f.polizaId}/siniestros`,f);await loadClaims(f.polizaId);msg.value=''}catch(e){msg.value=errorMessage(e)}}
async function updateState(claim:Siniestro){if(!selected.value)return;updating.value=claim.id;msg.value='';try{await api.patch(`/polizas/${selected.value.id}/siniestros/${claim.id}/estado`,{estado:stateEdits[claim.id]});await loadClaims(selected.value.id)}catch(e){msg.value=errorMessage(e)}finally{updating.value=''}}
async function renew(p:Poliza){msg.value='';success.value='';renewing.value=p.id;try{await api.post(`/renovaciones/poliza/${p.id}/evaluar`);success.value=`Evaluación de renovación generada para la póliza ${p.numero}.`}catch(e){msg.value=errorMessage(e)}finally{renewing.value=''}}
onMounted(async()=>{try{await Promise.all([load(),loadCatalogs(),loadPending()])}catch(e){msg.value=errorMessage(e)}});
</script>
<template><div class="page-head"><div><span class="eyebrow">Cartera</span><h2>Pólizas y siniestros</h2><p>Emite contratos y registra eventos ocurridos durante la vigencia.</p></div></div>
<div class="panel issue-box"><h3>Cotizaciones aceptadas pendientes de emisión</h3><form class="inline-form" @submit.prevent="issue"><select v-model="emit.cotizacionId" required><option value="">Seleccione una cotización…</option><option v-for="q in pending" :key="q.id" :value="q.id">{{quoteLabel(q)}}</option></select><input v-model="emit.inicioVigencia" type="date" required/><button class="primary">Emitir póliza</button></form><small v-if="emit.cotizacionId">{{emit.cotizacionId}}</small><div v-if="!pending.length" class="empty">No existen cotizaciones aceptadas pendientes.</div><div v-if="msg&&!show" class="alert error" role="alert">{{msg}}</div><div v-if="success&&!show" class="alert success" role="status">{{success}}</div></div>
<div class="panel table-panel"><div class="inline-form"><select v-model="estado" @change="load"><option value="">Todos los estados</option><option>VIGENTE</option><option>VENCIDA</option><option>CANCELADA</option><option>RENOVADA</option></select></div><table><thead><tr><th>Póliza</th><th>Prima</th><th>Vigencia</th><th>Estado</th><th></th></tr></thead><tbody><tr v-for="p in list" :key="p.id"><td><strong>{{p.numero}}</strong><small>{{p.id}}</small></td><td>{{p.moneda}} {{Number(p.prima).toFixed(2)}}</td><td>{{p.inicio}} → {{p.fin}}</td><td><StatusBadge :value="p.estado"/></td><td class="actions"><button class="secondary" @click="open(p)">Siniestros</button><button class="secondary" :disabled="renewing===p.id" @click="renew(p)">{{renewing===p.id?'Evaluando…':'Evaluar renovación'}}</button></td></tr><tr v-if="!list.length"><td colspan="5" class="empty">No existen pólizas emitidas.</td></tr></tbody></table></div>
<UiModal :title="`Siniestros · ${selected?.numero||''}`" :show="show" @close="show=false"><div class="mini-list claim-list"><div v-for="x in sin[selected?.id||'']" :key="x.id"><div class="claim-info"><strong>{{x.tipo}} · S/ {{Number(x.montoEstimado).toFixed(2)}}</strong><small>{{x.fecha}} · {{x.gravedad}}</small><StatusBadge :value="x.estado"/></div><div class="claim-state"><select v-model="stateEdits[x.id]" :disabled="x.estado==='LIQUIDADO'||x.estado==='RECHAZADO'"><option>REPORTADO</option><option>EN_EVALUACION</option><option>LIQUIDADO</option><option>RECHAZADO</option></select><button class="secondary" :disabled="updating===x.id||stateEdits[x.id]===x.estado||x.estado==='LIQUIDADO'||x.estado==='RECHAZADO'" @click="updateState(x)">{{updating===x.id?'Guardando…':'Actualizar estado'}}</button></div></div></div><div v-if="msg" class="alert error">{{msg}}</div>
<h3>Registrar siniestro</h3><form class="form-grid" @submit.prevent="saveS"><label>Fecha<input v-model="f.fecha" type="date"/></label><label>Tipo<input v-model="f.tipo"/></label><label>Monto estimado<input v-model.number="f.montoEstimado" type="number"/></label><label>Gravedad<select v-model="f.gravedad"><option>LEVE</option><option>MODERADO</option><option>GRAVE</option></select></label><label>Estado<select v-model="f.estado"><option>REPORTADO</option><option>EN_EVALUACION</option><option>LIQUIDADO</option><option>RECHAZADO</option></select></label><label class="check"><input v-model="f.responsabilidadAsegurado" type="checkbox"/>Responsabilidad del asegurado</label><button class="primary full">Registrar siniestro</button></form></UiModal></template>
