<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import api, { errorMessage } from '@/services/api';
import type { Poliza, Renovacion } from '@/types';
import StatusBadge from '@/components/StatusBadge.vue';
import UiModal from '@/components/UiModal.vue';
const policies=ref<Poliza[]>([]),history=ref<Renovacion[]>([]),selectedPolicyId=ref(''),selected=ref<Renovacion|null>(null),detailItem=ref<Renovacion|null>(null),showDetail=ref(false),loading=ref(false),action=ref(''),message=ref(''),success=ref('');
const currentPolicy=computed(()=>policies.value.find(p=>p.id===selectedPolicyId.value));
const canDecide=computed(()=>selected.value&&['AUTOMATICA','REQUIERE_RECALCULO','EVALUACION_MANUAL','PENDIENTE'].includes(selected.value.estado));
const decisionLabel=(state:string)=>({AUTOMATICA:'Renovación automática',REQUIERE_RECALCULO:'Recálculo de prima',EVALUACION_MANUAL:'Evaluación manual',ACEPTADA:'Propuesta aprobada',RECHAZADA:'Propuesta rechazada',VENCIDA:'Propuesta vencida'}[state]||state);
async function loadPolicies(){const data:Poliza[]=(await api.get('/polizas')).data;policies.value=data.filter(p=>p.estado==='VIGENTE');if(!selectedPolicyId.value&&policies.value.length)selectedPolicyId.value=policies.value[0].id;await loadHistory()}
async function loadHistory(){selected.value=null;message.value='';try{history.value=selectedPolicyId.value?(await api.get(`/renovaciones/poliza/${selectedPolicyId.value}/historial`)).data:[];if(history.value.length)selected.value=history.value[0]}catch(e){history.value=[];message.value=errorMessage(e)}}
async function run(label:string,operation:()=>Promise<void>){message.value='';success.value='';action.value=label;try{await operation()}catch(e){message.value=errorMessage(e)}finally{action.value=''}}
async function evaluate(){if(!selectedPolicyId.value)return;loading.value=true;await run('evaluar',async()=>{await api.post(`/renovaciones/poliza/${selectedPolicyId.value}/evaluar`);success.value='Evaluación generada correctamente.';await loadHistory()});loading.value=false}
async function decide(decision:'aprobar'|'rechazar'){if(!selected.value)return;await run(decision,async()=>{selected.value=(await api.patch(`/renovaciones/${selected.value!.id}/${decision}`)).data;success.value=decision==='aprobar'?'Propuesta aprobada.':'Propuesta rechazada.';await loadHistory()})}
async function generatePolicy(){if(!selected.value)return;await run('generar',async()=>{const policy:Poliza=(await api.post(`/renovaciones/${selected.value!.id}/generar-poliza`)).data;success.value=`Póliza ${policy.numero} generada correctamente.`;await loadPolicies()})}
function show(item:Renovacion){detailItem.value=item;showDetail.value=true}
onMounted(async()=>{loading.value=true;try{await loadPolicies()}catch(e){message.value=errorMessage(e)}finally{loading.value=false}});
</script>
<template>
<div class="page-head"><div><span class="eyebrow">Ciclo de vida</span><h2>Renovación de pólizas</h2><p>Evalúa siniestralidad, decide propuestas y genera la siguiente vigencia.</p></div></div>
<div class="panel renewal-workflow"><div class="renew-selector"><label>Póliza vigente<select v-model="selectedPolicyId" :disabled="loading" @change="loadHistory"><option value="">Seleccione una póliza…</option><option v-for="p in policies" :key="p.id" :value="p.id">{{p.numero}} · {{p.moneda}} {{Number(p.prima).toFixed(2)}} · vence {{p.fin}}</option></select></label><button class="primary" :disabled="!selectedPolicyId||loading||!!action" @click="evaluate">{{action==='evaluar'?'Evaluando…':'Evaluar renovación'}}</button></div><div v-if="currentPolicy" class="policy-summary"><span>Póliza <b>{{currentPolicy.numero}}</b></span><span>Prima vigente <b>{{currentPolicy.moneda}} {{Number(currentPolicy.prima).toFixed(2)}}</b></span><span>Vigencia <b>{{currentPolicy.inicio}} → {{currentPolicy.fin}}</b></span></div><div v-if="message" class="alert error">{{message}}</div><div v-if="success" class="alert success">{{success}}</div><div v-if="!policies.length&&!loading" class="empty">No hay pólizas vigentes disponibles para evaluar.</div></div>
<div v-if="selected" class="panel renewal-detail"><div class="quote-top"><div><span class="eyebrow">Resultado de evaluación</span><h3>{{decisionLabel(selected.estado)}}</h3></div><StatusBadge :value="selected.estado"/></div><div class="renew-metrics"><div><small>Prima anterior</small><b>S/ {{Number(selected.primaAnterior).toFixed(2)}}</b></div><div><small>Nueva prima</small><b>S/ {{Number(selected.nuevaPrima).toFixed(2)}}</b></div><div><small>Variación</small><b :class="{up:selected.porcentajeVariacion>0}">{{selected.porcentajeVariacion>0?'+':''}}{{Number(selected.porcentajeVariacion).toFixed(2)}}%</b></div><div><small>Siniestros considerados</small><b>{{selected.siniestrosConsiderados}}</b></div></div><div class="decision-reason"><small>Motivo de la decisión</small><p>{{selected.motivo}}</p></div><div class="renew-actions"><button v-if="canDecide" class="primary" :disabled="!!action" @click="decide('aprobar')">{{action==='aprobar'?'Aprobando…':'Aprobar propuesta'}}</button><button v-if="canDecide" class="secondary danger" :disabled="!!action" @click="decide('rechazar')">{{action==='rechazar'?'Rechazando…':'Rechazar propuesta'}}</button><button v-if="selected.estado==='ACEPTADA'&&!selected.polizaRenovadaId" class="primary" :disabled="!!action" @click="generatePolicy">{{action==='generar'?'Generando…':'Generar nueva póliza'}}</button><RouterLink v-if="selected.polizaRenovadaId" class="secondary" to="/polizas">Ver póliza generada</RouterLink></div></div>
<div class="panel table-panel renewal-history"><div class="history-title"><h3>Historial de evaluaciones</h3><small>{{history.length}} evaluación(es) para la póliza seleccionada</small></div><table><thead><tr><th>Fecha</th><th>Decisión</th><th>Primas</th><th>Variación</th><th>Siniestros</th><th>Resultado</th><th></th></tr></thead><tbody><tr v-for="item in history" :key="item.id"><td>{{new Date(item.creadaEn).toLocaleString()}}</td><td>{{decisionLabel(item.estado)}}</td><td><strong>S/ {{Number(item.nuevaPrima).toFixed(2)}}</strong><small>Antes: S/ {{Number(item.primaAnterior).toFixed(2)}}</small></td><td>{{Number(item.porcentajeVariacion).toFixed(2)}}%</td><td>{{item.siniestrosConsiderados}}</td><td><StatusBadge :value="item.estado"/></td><td><button class="secondary" @click="show(item)">Ver detalle</button></td></tr><tr v-if="!history.length"><td colspan="7" class="empty">Aún no hay evaluaciones para esta póliza.</td></tr></tbody></table></div>
<UiModal title="Detalle de evaluación" :show="showDetail" @close="showDetail=false"><div v-if="detailItem" class="renewal-modal-detail"><div class="quote-top"><div><small>{{new Date(detailItem.creadaEn).toLocaleString()}}</small><h3>{{decisionLabel(detailItem.estado)}}</h3></div><StatusBadge :value="detailItem.estado"/></div><div class="renew-metrics"><div><small>Prima anterior</small><b>S/ {{Number(detailItem.primaAnterior).toFixed(2)}}</b></div><div><small>Nueva prima</small><b>S/ {{Number(detailItem.nuevaPrima).toFixed(2)}}</b></div><div><small>Variación</small><b :class="{up:detailItem.porcentajeVariacion>0}">{{detailItem.porcentajeVariacion>0?'+':''}}{{Number(detailItem.porcentajeVariacion).toFixed(2)}}%</b></div><div><small>Siniestros considerados</small><b>{{detailItem.siniestrosConsiderados}}</b></div></div><div class="decision-reason"><small>Motivo de la decisión</small><p>{{detailItem.motivo}}</p></div><div class="renewal-trace"><p><b>ID de propuesta:</b> {{detailItem.id}}</p><p><b>Póliza de origen:</b> {{detailItem.polizaOrigenId}}</p><p><b>Válida hasta:</b> {{new Date(detailItem.venceEn).toLocaleString()}}</p><p v-if="detailItem.decididaEn"><b>Decidida el:</b> {{new Date(detailItem.decididaEn).toLocaleString()}}</p><p v-if="detailItem.polizaRenovadaId"><b>Póliza generada:</b> {{detailItem.polizaRenovadaId}}</p></div></div></UiModal>
</template>
