<script setup lang="ts">
import{onMounted,reactive,ref}from'vue';import api,{errorMessage}from'@/services/api';import type{Tabla,TablaDetalle}from'@/types';import UiModal from'@/components/UiModal.vue';import StatusBadge from'@/components/StatusBadge.vue';
const list=ref<Tabla[]>([]),show=ref(false),showDetail=ref(false),detail=ref<TablaDetalle|null>(null),loadingDetail=ref(false),msg=ref(''),formError=ref(''),saving=ref(false);
const f=reactive<any>({codigo:'AUT-PAR',version:1,tipoVehiculo:'AUTO',tipoUso:'PARTICULAR',primaBase:1200,primaMinima:700,inicioVigencia:new Date().toISOString().slice(0,10),finVigencia:`${new Date().getFullYear()+1}-12-31`,codigoNotaTecnica:'NT-VEH-001',estado:'VIGENTE',factores:[{codigo:'EDAD',nombre:'Edad del conductor',tipoVariable:'EDAD',valorMinimo:18,valorMaximo:80,multiplicador:1.05,orden:1}]});
async function load(){msg.value='';try{list.value=(await api.get('/tablas-tarifarias')).data}catch(e){msg.value=errorMessage(e)}}async function save(){formError.value='';saving.value=true;try{await api.post('/tablas-tarifarias',f);show.value=false;await load()}catch(e){formError.value=errorMessage(e)}finally{saving.value=false}}function openCreate(){formError.value='';show.value=true}function closeCreate(){formError.value='';show.value=false}function add(){f.factores.push({codigo:'',nombre:'',tipoVariable:'',valorMinimo:0,valorMaximo:100,multiplicador:1,orden:f.factores.length+1})}
async function openDetail(id:string){loadingDetail.value=true;msg.value='';try{detail.value=(await api.get(`/tablas-tarifarias/${id}`)).data;showDetail.value=true}catch(e){msg.value=errorMessage(e)}finally{loadingDetail.value=false}}onMounted(load);
</script>
<template><div class="page-head"><div><span class="eyebrow">Motor de riesgo</span><h2>Tablas tarifarias</h2><p>Versiona primas base, mínimos y factores aplicables.</p></div><button class="primary" @click="openCreate">+ Nueva tabla</button></div><div v-if="msg" class="alert error">{{msg}}</div>
<div class="cards"><div class="tariff-card" v-for="x in list" :key="x.id"><div><span>{{x.codigo}} · v{{x.version}}</span><StatusBadge :value="x.estado"/></div><h3>{{x.tipoVehiculo}} / {{x.tipoUso}}</h3><b>S/ {{Number(x.primaBase).toFixed(2)}}</b><small>Prima mínima S/ {{Number(x.primaMinima).toFixed(2)}}</small><hr/><small>{{x.inicio}} → {{x.fin}}</small><small>Nota técnica: {{x.notaTecnica}}</small><button class="secondary wide tariff-detail-btn" :disabled="loadingDetail" @click="openDetail(x.id)">Ver detalle</button></div></div><div v-if="!list.length" class="panel empty">No hay tablas registradas.</div>
<UiModal title="Registrar tabla tarifaria" :show="show" @close="closeCreate"><form class="form-grid" @submit.prevent="save"><label>Código<input v-model="f.codigo"/></label><label>Versión<input v-model.number="f.version" type="number"/></label><label>Tipo vehículo<select v-model="f.tipoVehiculo"><option>AUTO</option><option>CAMIONETA</option><option>MOTO</option></select></label><label>Uso<select v-model="f.tipoUso"><option>PARTICULAR</option><option>TAXI</option><option>CARGA</option></select></label><label>Prima base<input v-model.number="f.primaBase" type="number" step=".01"/></label><label>Prima mínima<input v-model.number="f.primaMinima" type="number" step=".01"/></label><label>Inicio<input v-model="f.inicioVigencia" type="date"/></label><label>Fin<input v-model="f.finVigencia" type="date"/></label><label>Nota técnica<input v-model="f.codigoNotaTecnica"/></label><label>Estado<select v-model="f.estado"><option>VIGENTE</option><option>BORRADOR</option><option>VENCIDA</option></select></label><div class="full factor-box"><div class="factor-head"><h3>Factores de riesgo</h3><button type="button" class="secondary" @click="add">Agregar</button></div><div class="factor-row" v-for="(x,i) in f.factores" :key="i"><input v-model="x.codigo" placeholder="Código"/><input v-model="x.nombre" placeholder="Nombre"/><input v-model="x.tipoVariable" placeholder="Variable"/><input v-model.number="x.multiplicador" type="number" step=".01"/></div></div><div v-if="formError" class="alert error full" role="alert">{{formError}}</div><button class="primary full" :disabled="saving">{{saving?'Guardando…':'Guardar tabla'}}</button></form></UiModal>
<UiModal :title="`Detalle · ${detail?.codigo||''} v${detail?.version||''}`" :show="showDetail" @close="showDetail=false"><div v-if="detail" class="tariff-detail"><div class="renew-metrics"><div><small>Prima base</small><b>S/ {{Number(detail.primaBase).toFixed(2)}}</b></div><div><small>Prima mínima</small><b>S/ {{Number(detail.primaMinima).toFixed(2)}}</b></div><div><small>Vehículo / uso</small><b>{{detail.tipoVehiculo}} / {{detail.tipoUso}}</b></div><div><small>Estado</small><StatusBadge :value="detail.estado"/></div></div><p><b>Vigencia:</b> {{detail.inicio}} → {{detail.fin}}</p><p><b>Nota técnica:</b> {{detail.notaTecnica}}</p><h3>Factores de riesgo</h3><div class="panel table-panel"><table><thead><tr><th>Orden</th><th>Código</th><th>Factor</th><th>Rango</th><th>Multiplicador</th></tr></thead><tbody><tr v-for="x in detail.factores" :key="x.codigo"><td>{{x.orden}}</td><td>{{x.codigo}}</td><td><strong>{{x.nombre}}</strong><small>{{x.tipoVariable}}</small></td><td>{{x.valorMinimo}} – {{x.valorMaximo}}</td><td>{{Number(x.multiplicador).toFixed(4)}}x</td></tr><tr v-if="!detail.factores.length"><td colspan="5" class="empty">Sin factores configurados.</td></tr></tbody></table></div></div></UiModal></template>
